## Project
name: dbt_demo
version: "1.0"
config-version: 2
profile: snowflake_demo

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  dbt_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
